### ISSUE TITLE
Please !!! Can you fix it ?

### ISSUE THREAD

**Issue by wQuick** [andersardo/gramps_Treemerge#3]
![image](https://github.com/andersardo/gramps_Treemerge/assets/4439940/6d729a24-208c-498c-85c1-1211051c1f98)

**Comment by andersardo** [comment]
Can you provide more information on your environment?

**Comment by wQuick** [comment]
Hello!!  I think that I should be wrong, but a I write this change in ftDatabase.py

#person = ' OR '.join(row['person'].split())
person = ' OR '.join('"{0}"'.format(w) for w in row['person'].split())

Can you fix it ??

Thank you.

**Comment by andersardo** [comment]
Sorry I can't recreate the error :-(

**Comment by wQuick** [comment]
Can you test with person with multiple surname or with alternative name with multiple surname ?

Thank you 

![image](https://github.com/andersardo/gramps_Treemerge/assets/4439940/49fee604-738f-4990-8eb5-0bd5004a5d17)

**Comment by andersardo** [comment]
Multiple surnames seem to work fine.
But I found a bug where dates of type 'around' caused a failure in sqlite queries at same spot that you reported.
Fixed by your proposal above - thanks!
